### ISSUE TITLE
Deadlock during nccl.bcast

### ISSUE THREAD

**Issue by colesbury** [ngimel/nccl.torch#3]
I observed a deadlock in nccl.bcast (4 GPUs) when called from nn.DataParallelTable. The deadlock occurs when a LuaJIT garbage collection step happens to trigger a cudaFree call in between the ncclBcast kernel launches.

https://github.com/ngimel/nccl.torch/blob/master/init.lua#L113-L117

Here's a step-by-step description of what I'm seeeing:
1) DataParallelTable:syncParameters calls nccl.bcast() (4 GPUs)
2) nccl.bcast successfully launches the first three ncclBcast kernels
3) The fourth time through the loop, the call to `inputs[i]:data()` happens to trigger a LuaJIT GC step
4) The LuaJIT garbage collector collects an unrelated CudaTensor; this calls cudaFree
5) Deadlock!

I think the deadlock happens because cudaFree causes a synchronization, but the first three ncclBcast kernels won't finish until the fourth launches. 

The only robust fix I can think of is to move these lines from Lua into C to avoid any potential cudaFree calls via the garbage collector:
https://github.com/ngimel/nccl.torch/blob/master/init.lua#L113-L117

This probably also occurs in other nccl functions.

**Comment by colesbury** [comment]
Actually, there's a simpler solution than moving the loop into C. Lua supports stopping and restarting the garbage collector via `collectgarbage("stop")` and `collectgarbage("restart")`

http://www.lua.org/manual/5.1/manual.html#pdf-collectgarbage

**Comment by ngimel** [comment]
@colesbury Can I pull in your latest commit disabling garbage collection and close the issue? Thanks!

**Comment by colesbury** [comment]
Yes, please!
