### ISSUE TITLE
Error on all_reduce_test/all_gather_test with Tesla M2070  + CUDA 7.0

### ISSUE THREAD

**Issue by InnovArul** [ngimel/nccl.torch#7]
I would like get a hint on the issue I am facing.

```
-> % ./build/test/single/all_gather_test 10000000
 # Using devices
 #   Rank  0 uses device  0 [0x06] Tesla M2070
 #   Rank  1 uses device  1 [0x14] Tesla M2070
 #   Rank  2 uses device  2 [0x11] Tesla M2070

 #      bytes             N    type     time  algbw  busbw    delta
 CuRAND error 204 at test/include/test_utilities.h:112
```

Itseems that there is some issue with pseudo random number generation.
Code 204 belongs to CURAND_STATUS_ARCH_MISMATCH, which means this GPU does not support this feature.

How to decide whether a GPU will support nccl? Is there any baseline for GPUs like compute capability, driver version etc?

Thanks!

**Comment by ngimel** [comment]
You should have opened an issue in nccl repository, https://github.com/NVIDIA/nccl. nccl repository readme page states that you need "Kepler or newer GPUs", you have Fermi. Closing.
